# Generated by Django 3.2.16 on 2023-01-16 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=8)),
                ('email', models.EmailField(max_length=150)),
                ('secondary_education', models.CharField(max_length=150)),
                ('tertiary_education', models.CharField(max_length=150)),
                ('degree_name', models.CharField(max_length=150)),
                ('skill_set', models.TextField(max_length=900)),
                ('personal_statement', models.TextField(max_length=2000)),
                ('previous_work', models.TextField(max_length=2000)),
            ],
        ),
    ]
